apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: php-7-4-2024-11-07-0306
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: false
spec:
  classRef: php
  config:
    image: ghcr.io/labring-actions/devbox/php-7.4:ec015f
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: php 7.4
  version: "7.4"
  runtimeVersion: 2024-11-07-0306
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: php
spec:
  title: "PHP"
  kind: Language
  description: php
