apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: java-openjdk17-2024-11-12-0310
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: java
  config:
    image: ghcr.io/labring-actions/devbox/java-openjdk17:da7a93f
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: java openjdk17
  version: "openjdk17"
  runtimeVersion: 2024-11-12-0310
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: java
spec:
  title: "java"
  kind: Language
  description: java
