apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: astro-4-10-0-2024-10-28-0326
  namespace: devbox-system
spec:
  classRef: astro
  config:
    image: ghcr.io/labring-actions/devbox/astro-4.10.0:5034c7a
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 4321
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: astro 4.10.0
  version: "4.10.0"
  runtimeVersion: 2024-10-28-0326
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: astro
spec:
  title: "astro"
  kind: Framework
  description: astro
