apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: astro-4-10-0
  namespace: devbox-system
spec:
  classRef: astro
  config:
    image: ghcr.io/labring-actions/devbox/astro-4.10.0:c843b6d
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 4321
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: astro 4.10.0
  version: "4.10.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: astro
spec:
  title: "astro"
  kind: Framework
  description: astro
