apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: rust-1-81-0-2024-10-25-0719
  namespace: devbox-system
spec:
  classRef: rust
  config:
    image: ghcr.io/labring-actions/devbox/rust-1.81.0:669362
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: rust 1.81.0
  version: "1.81.0"
  runtimeVersion: 2024-10-25-0719
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: rust
spec:
  title: "rust"
  kind: Language
  description: rust
