apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: php-8-2-20-2024-11-13-0347
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "true"
spec:
  classRef: php
  config:
    image: ghcr.io/labring-actions/devbox/php-8.2.20:248085
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: php 8.2.20
  version: "8.2.20"
  runtimeVersion: 2024-11-13-0347
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: php
spec:
  title: "PHP"
  kind: Language
  description: php
