apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: rocket-0-5-1-2024-11-13-0721
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: rocket
  config:
    image: ghcr.io/labring-actions/devbox/rocket-0.5.1:5365cd6
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: rocket 0.5.1
  version: "0.5.1"
  runtimeVersion: 2024-11-13-0721
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: rocket
spec:
  title: "rocket"
  kind: Framework
  description: rocket
