apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: quarkus-3-16-1-2024-11-01-0734
  namespace: devbox-system
spec:
  classRef: quarkus
  config:
    image: ghcr.io/labring-actions/devbox/quarkus-3.16.1:08d9f99
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: quarkus 3.16.1
  version: "3.16.1"
  runtimeVersion: 2024-11-01-0734
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: quarkus
spec:
  title: "quarkus"
  kind: Framework
  description: quarkus
