apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: gin
spec:
  title: gin
  classRef: gin
  description: "gin"
  config:
    user: sealos
    image: ghcr.io/labring-actions/devbox/gin:dad1de
  category:
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: gin
spec:
  title: gin
  kind: Framework
  description: "gin"
