apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: c-gcc-12-2-0-2024-11-01-1132
  namespace: devbox-system
spec:
  classRef: c
  config:
    image: ghcr.io/labring-actions/devbox/c-gcc-12.2.0:de143e
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: c gcc-12.2.0
  version: "gcc-12.2.0"
  runtimeVersion: 2024-11-01-1132
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: c
spec:
  title: "c"
  kind: Language
  description: c
