apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: go-1-22-5
  namespace: devbox-system
spec:
  classRef: go
  config:
    image: ghcr.io/labring-actions/devbox/go-1.22.5:f59e2a
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
  description: go 1.22.5
  version: 1.22.5
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: go
spec:
  title: go
  kind: Language
  description: go
