apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: chi-v5-1-0
  namespace: devbox-system
spec:
  classRef: chi
  config:
    image: ghcr.io/labring-actions/devbox/chi-v5.1.0:1f897b2
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: chi v5.1.0
  version: "v5.1.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: chi
spec:
  title: "chi"
  kind: Framework
  description: chi
