apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: chi-v5-1-0-2024-11-13-0721
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: chi
  config:
    image: ghcr.io/labring-actions/devbox/chi-v5.1.0:5365cd6
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: chi v5.1.0
  version: "v5.1.0"
  runtimeVersion: 2024-11-13-0721
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: chi
spec:
  title: "chi"
  kind: Framework
  description: chi
