apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: flask-3-0-3
  namespace: devbox-system
spec:
  classRef: flask
  config:
    image: ghcr.io/labring-actions/devbox/flask-3.0.3:8086af
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: flask 3.0.3
  version: "3.0.3"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: flask
spec:
  title: "flask"
  kind: Framework
  description: flask
