apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: nuxt3-v3-13-2024-11-13-0835
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: nuxt3
  config:
    image: ghcr.io/labring-actions/devbox/nuxt3-v3.13:3ac184e
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: nuxt3 v3.13
  version: "v3.13"
  runtimeVersion: 2024-11-13-0835
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: nuxt3
spec:
  title: "nuxt3"
  kind: Framework
  description: nuxt3
