apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: nuxt3-v3-13
  namespace: devbox-system
spec:
  classRef: nuxt3
  config:
    image: ghcr.io/labring-actions/devbox/nuxt3-v3.13:e63e16e
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: nuxt3 v3.13
  version: "v3.13"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: nuxt3
spec:
  title: "nuxt3"
  kind: Framework
  description: nuxt3
