apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: next.js-14-2-5-2024-12-20-0305
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: next.js
  config:
    image: ghcr.io/labring-actions/devbox/next.js-14.2.5:4fa844
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: next.js 14.2.5
  version: "14.2.5"
  runtimeVersion: 2024-12-20-0305
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: next.js
spec:
  title: "Next.js"
  kind: Framework
  description: next.js
