apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: umi-4-3-27-2024-11-19-0839
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: umi
  config:
    image: ghcr.io/labring-actions/devbox/umi-4.3.27:22f026
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: umi 4.3.27
  version: "4.3.27"
  runtimeVersion: 2024-11-19-0839
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: umi
spec:
  title: "UmiJS"
  kind: Framework
  description: umi
