apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: spring-boot-3-3-2-2024-11-13-0740
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: spring-boot
  config:
    image: ghcr.io/labring-actions/devbox/spring-boot-3.3.2:a9e413
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: spring-boot 3.3.2
  version: "3.3.2"
  runtimeVersion: 2024-11-13-0740
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: spring-boot
spec:
  title: "Spring Boot"
  kind: Framework
  description: spring-boot
