apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: iris-v12-2-11-2024-10-25-1000
  namespace: devbox-system
spec:
  classRef: iris
  config:
    image: ghcr.io/labring-actions/devbox/iris-v12.2.11:1a7252e
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: iris v12.2.11
  version: "v12.2.11"
  runtimeVersion: 2024-10-25-1000
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: iris
spec:
  title: "iris"
  kind: Framework
  description: iris
