apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: ubuntu-24-04-2024-11-01-1417
  namespace: devbox-system
spec:
  classRef: ubuntu
  config:
    image: ghcr.io/labring-actions/devbox/ubuntu-24.04:2ec65d2
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: ubuntu 24.04
  version: "24.04"
  runtimeVersion: 2024-11-01-1417
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: ubuntu
spec:
  title: "ubuntu"
  kind: OS
  description: ubuntu
