apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: django-4-2-16
  namespace: devbox-system
spec:
  classRef: django
  config:
    image: ghcr.io/labring-actions/devbox/django-4.2.16:148fcbe
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: django 4.2.16
  version: "4.2.16"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: django
spec:
  title: "django"
  kind: Framework
  description: django
