apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: gin-v1-10-0
  namespace: devbox-system
spec:
  classRef: gin
  config:
    image: ghcr.io/labring-actions/devbox/gin-v1.10.0:b7f162
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
  description: gin v1.10.0
  version: "v1.10.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: gin
spec:
  title: gin
  kind: Framework
  description: gin
