apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: go-1-22-5-2024-10-25-0704
  namespace: devbox-system
spec:
  classRef: go
  config:
    image: ghcr.io/labring-actions/devbox/go-1.22.5:d988c90
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: go 1.22.5
  version: "1.22.5"
  runtimeVersion: 2024-10-25-0704
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: go
spec:
  title: "go"
  kind: Language
  description: go
