apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: python-3-11-2024-10-25-0719
  namespace: devbox-system
spec:
  classRef: python
  config:
    image: ghcr.io/labring-actions/devbox/python-3.11:6693628
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: python 3.11
  version: "3.11"
  runtimeVersion: 2024-10-25-0719
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: python
spec:
  title: "python"
  kind: Language
  description: python
