apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: hugo-v0-135-0-2024-11-13-0740
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: hugo
  config:
    image: ghcr.io/labring-actions/devbox/hugo-v0.135.0:a9e4136
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 1313
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: hugo v0.135.0
  version: "v0.135.0"
  runtimeVersion: 2024-11-13-0740
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: hugo
spec:
  title: "hugo"
  kind: Framework
  description: hugo
