apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: hugo-v0-135-0
  namespace: devbox-system
spec:
  classRef: hugo
  config:
    image: ghcr.io/labring-actions/devbox/hugo-v0.135.0:e85d2a1
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 1313
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: hugo v0.135.0
  version: "v0.135.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: hugo
spec:
  title: "hugo"
  kind: Framework
  description: hugo
