apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: react-18-2-0-2024-11-18-0957
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: react
  config:
    image: ghcr.io/labring-actions/devbox/react-18.2.0:c71eb2
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: react 18.2.0
  version: "18.2.0"
  runtimeVersion: 2024-11-18-0957
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: react
spec:
  title: "react"
  kind: Framework
  description: react
