apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: svelte-6-4-0-2024-11-13-0835
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: svelte
  config:
    image: ghcr.io/labring-actions/devbox/svelte-6.4.0:3ac184e
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 5173
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: svelte 6.4.0
  version: "6.4.0"
  runtimeVersion: 2024-11-13-0835
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: svelte
spec:
  title: "SvelteKit"
  kind: Framework
  description: svelte
