apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: pytorch-pytorch-2024-12-10-0535
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: pytorch
  config:
    image: ghcr.io/labring-actions/devbox/pytorch-pytorch:769de7
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: pytorch pytorch
  version: "pytorch"
  runtimeVersion: 2024-12-10-0535
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: pytorch
spec:
  title: "pytorch"
  kind: Framework
  description: pytorch
