apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: echo-v4-12-0
  namespace: devbox-system
spec:
  classRef: echo
  config:
    image: ghcr.io/labring-actions/devbox/echo-v4.12.0:c1294f
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: echo v4.12.0
  version: "v4.12.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: echo
spec:
  title: "8080"
  kind: Framework
  description: echo
