apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: echo-v4-12-0-2024-10-25-0818
  namespace: devbox-system
spec:
  classRef: echo
  config:
    image: ghcr.io/labring-actions/devbox/echo-v4.12.0:73038f
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: echo v4.12.0
  version: "v4.12.0"
  runtimeVersion: 2024-10-25-0818
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: echo
spec:
  title: "echo"
  kind: Framework
  description: echo
