apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: docusaurus-3-5-2-2024-11-18-0957
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: docusaurus
  config:
    image: ghcr.io/labring-actions/devbox/docusaurus-3.5.2:c71eb28
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: docusaurus 3.5.2
  version: "3.5.2"
  runtimeVersion: 2024-11-18-0957
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: docusaurus
spec:
  title: "docusaurus"
  kind: Framework
  description: docusaurus
