apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: ubuntu-cuda-24-04-2024-12-11-0729
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: ubuntu-cuda
  category: 
  - gpu
  config:
    image: crpi-0cfxxemn813jdhyg.cn-hangzhou.personal.cr.aliyuncs.com/cbluebird/ubuntu-cuda:latest
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: root
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: ubuntu-cuda 24.04
  version: "24.04"
  runtimeVersion: 2024-12-11-0729
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: ubuntu-cuda
spec:
  title: "ubuntu-cuda"
  kind: OS
  description: ubuntu-cuda
