apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: net-8-0
  namespace: devbox-system
spec:
  classRef: net
  config:
    image: ghcr.io/labring-actions/devbox/net-8.0:a5c4dc
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: net 8.0
  version: "8.0"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: net
spec:
  title: ".Net"
  kind: Language
  description: net
