apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: net-8-0-2024-10-25-0711
  namespace: devbox-system
spec:
  classRef: net
  config:
    image: ghcr.io/labring-actions/devbox/net-8.0:b3361c
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: net 8.0
  version: "8.0"
  runtimeVersion: 2024-10-25-0711
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: net
spec:
  title: ".Net"
  kind: Language
  description: net
