apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: gin-v1-10-0-2024-10-25-0818
  namespace: devbox-system
spec:
  classRef: gin
  config:
    image: ghcr.io/labring-actions/devbox/gin-v1.10.0:73038fa
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: gin v1.10.0
  version: "v1.10.0"
  runtimeVersion: 2024-10-25-0818
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: gin
spec:
  title: "gin"
  kind: Framework
  description: gin
