apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: python-3-12-2024-10-29-0754
  namespace: devbox-system
spec:
  classRef: python
  config:
    image: ghcr.io/labring-actions/devbox/python-3.12:7d734d3
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: python 3.12
  version: "3.12"
  runtimeVersion: 2024-10-29-0754
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: python
spec:
  title: "python"
  kind: Language
  description: python
