apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: angular-v18-2024-11-18-0957
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: angular
  config:
    image: ghcr.io/labring-actions/devbox/angular-v18:c71eb28
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 4200
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: angular v18
  version: "v18"
  runtimeVersion: 2024-11-18-0957
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: angular
spec:
  title: "angular"
  kind: Framework
  description: angular
