apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: flask-3-0-3-2024-10-28-0256
  namespace: devbox-system
spec:
  classRef: flask
  config:
    image: ghcr.io/labring-actions/devbox/flask-3.0.3:fd2491
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: flask 3.0.3
  version: "3.0.3"
  runtimeVersion: 2024-10-28-0256
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: flask
spec:
  title: "flask"
  kind: Framework
  description: flask
