apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: iris-v12-2-11
  namespace: devbox-system
spec:
  classRef: iris
  config:
    image: ghcr.io/labring-actions/devbox/iris-v12.2.11:d6d0c3
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: iris v12.2.11
  version: "v12.2.11"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: iris
spec:
  title: "iris"
  kind: Framework
  description: iris
