apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: node.js-20-2024-11-13-0700
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: node.js
  config:
    image: ghcr.io/labring-actions/devbox/node.js-20:1323f9
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: node.js 20
  version: "20"
  runtimeVersion: 2024-11-13-0700
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: node.js
spec:
  title: "node.js"
  kind: Language
  description: node.js
