apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: node.js-18
  namespace: devbox-system
spec:
  classRef: node.js
  config:
    image: ghcr.io/labring-actions/devbox/node.js-18:bf81c9
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    user: sealos
  description: node.js 18
  version: "18"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: node.js
spec:
  title: node.js
  kind: Language
  description: node.js
