apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: nodejs18
spec:
  title: nodejs18
  classRef: nodejs
  description: "nodejs18"
  config:
    user: sealos
    image: ghcr.io/labring-actions/devbox/nodejs18:b50472
  category:
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: nodejs
spec:
  title: nodejs
  kind: Language
  description: "nodejs"
