apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: angular-v18
  namespace: devbox-system
spec:
  classRef: angular
  config:
    image: ghcr.io/labring-actions/devbox/angular-v18:b95da0
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 4200
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: angular v18
  version: "v18"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: angular
spec:
  title: "angular"
  kind: Framework
  description: angular
