apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: express.js-4-21-0-2024-10-28-0312
  namespace: devbox-system
spec:
  classRef: express.js
  config:
    image: ghcr.io/labring-actions/devbox/express.js-4.21.0:c2b1fa9
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: express.js 4.21.0
  version: "4.21.0"
  runtimeVersion: 2024-10-28-0312
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: express.js
spec:
  title: "express.js"
  kind: Framework
  description: express.js
