apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: python-3-10
  namespace: devbox-system
spec:
  classRef: python
  config:
    image: ghcr.io/labring-actions/devbox/python-3.10:d4059a2
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: python 3.10
  version: "3.10"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: python
spec:
  title: "python"
  kind: Language
  description: python
