apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: umi-4-3-27
  namespace: devbox-system
spec:
  classRef: umi
  config:
    image: ghcr.io/labring-actions/devbox/umi-4.3.27:b266e6
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8000
        name: devbox-app-port
        protocol: TCP
    user: sealos
    workingDir: /home/sealos/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/sealos/project/entrypoint.sh
  description: umi 4.3.27
  version: "4.3.27"
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: umi
spec:
  title: "UmiJS"
  kind: Framework
  description: umi
