apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: vue-v3-4-29-2024-12-19-0744
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: vue
  config:
    image: ghcr.io/labring-actions/devbox/vue-v3.4.29:4f84e72
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 3000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: vue v3.4.29
  version: "v3.4.29"
  runtimeVersion: 2024-12-19-0744
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: vue
spec:
  title: "Vue.js"
  kind: Framework
  description: vue
