apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: django-4-2-16-2024-11-13-0721
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: django
  config:
    image: ghcr.io/labring-actions/devbox/django-4.2.16:5365cd
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8000
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: django 4.2.16
  version: "4.2.16"
  runtimeVersion: 2024-11-13-0721
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: django
spec:
  title: "django"
  kind: Framework
  description: django
