apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: cpp-gcc-12-2-0-2024-11-12-0651
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: cpp
  config:
    image: ghcr.io/labring-actions/devbox/cpp-gcc-12.2.0:13aacd8
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: cpp gcc-12.2.0
  version: "gcc-12.2.0"
  runtimeVersion: 2024-11-12-0651
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: cpp
spec:
  title: "C++"
  kind: Language
  description: cpp
