apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: vitepress-1-4-0-2024-11-18-0836
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: vitepress
  config:
    image: ghcr.io/labring-actions/devbox/vitepress-1.4.0:62f0cf
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 4173
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: vitepress 1.4.0
  version: "1.4.0"
  runtimeVersion: 2024-11-18-0836
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: vitepress
spec:
  title: "VitePress"
  kind: Framework
  description: vitepress
