apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: cpp-g++12-2-0-2024-10-30-0838
  namespace: devbox-system
spec:
  classRef: cpp
  config:
    image: ghcr.io/labring-actions/devbox/cpp-g++12.2.0:e79fb93
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: cpp g++12.2.0
  version: "g++12.2.0"
  runtimeVersion: 2024-10-30-0838
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: cpp
spec:
  title: "C++"
  kind: Language
  description: cpp
