apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: flask-3-0-3-2024-11-13-0721
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: flask
  config:
    image: ghcr.io/labring-actions/devbox/flask-3.0.3:5365cd6
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 8080
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: flask 3.0.3
  version: "3.0.3"
  runtimeVersion: 2024-11-13-0721
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: flask
spec:
  title: "flask"
  kind: Framework
  description: flask
