name: Build Runtime Cluster Image
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
          "yaml/cn/Framework/flask/3.0.3/3.0.3.yaml",
          "yaml/cn/Framework/vue/v3.4.29/v3.4.29.yaml",
          "yaml/cn/Framework/next.js/14.2.5/14.2.5.yaml",
          "yaml/cn/Framework/react/18.2.0/18.2.0.yaml",
          "yaml/cn/Framework/gin/v1.10.0/v1.10.0.yaml",
          "yaml/cn/Framework/spring-boot/3.3.2/3.3.2.yaml",
          "yaml/cn/Language/go/1.22.5/1.22.5.yaml",
          "yaml/cn/Language/go/1.23.0/1.23.0.yaml",
          "yaml/cn/Language/python/3.10/3.10.yaml",
          "yaml/cn/Language/python/3.11/3.11.yaml",
          "yaml/cn/Language/python/3.12/3.12.yaml",
          "yaml/cn/Language/rust/1.81.0/1.81.0.yaml",
          "yaml/cn/Language/java/openjdk17/openjdk17.yaml",
          "yaml/cn/Language/php/7.4/7.4.yaml",
          "yaml/cn/Language/php/8.2.20/8.2.20.yaml",
          "yaml/cn/Language/node.js/20/20.yaml",
          "yaml/cn/Language/node.js/18/18.yaml",
          "yaml/cn/Language/node.js/22/22.yaml",
          "yaml/cn/OS/debian-ssh/12.6/12.6.yaml",
        ]
      fail-fast: false
    env:
      RUNTIME_PATH: ${{ matrix.target }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set variables
        id: set_vars
        run: |
          RUNTIME_NAME=$(echo $RUNTIME_PATH | sed -E 's/.*\/([^/]+)\/([^/]+)\/.*\.yaml/\1-\2/' | tr '.' '-')
          COMMIT_ID=${{ github.sha }}
          SHORT_COMMIT_ID=${COMMIT_ID::6}
          CLUSTER_IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/sealos-cloud-devbox-runtime-$RUNTIME_NAME:$SHORT_COMMIT_ID
          echo "RUNTIME_NAME=$RUNTIME_NAME" >> $GITHUB_ENV
          echo "SHORT_COMMIT_ID=$SHORT_COMMIT_ID" >> $GITHUB_ENV
          echo "CLUSTER_IMAGE_NAME=$CLUSTER_IMAGE_NAME" >> $GITHUB_ENV
      - name: Set up sealos
        run: |
          curl -sfL https://raw.githubusercontent.com/labring/sealos/main/scripts/install.sh | sh -s v5.0.0 labring/sealos
      - name: Login to ghcr.io
        run: |
          sudo sealos login -u ${{ github.repository_owner }} -p ${{ secrets.GH_PAT }} ghcr.io
      - name: Build cluster image
        run: |
          echo "runtime_path: $RUNTIME_PATH"
          echo "runtime_name: $RUNTIME_NAME"
          echo "short_commit_id: $SHORT_COMMIT_ID"
          echo "cluster_image_name: $CLUSTER_IMAGE_NAME"
          sudo bash script/build_runtime_cluster_image.sh $RUNTIME_PATH $RUNTIME_NAME $CLUSTER_IMAGE_NAME
      - name: Push and save cluster image
        run: |
          sudo sealos push $CLUSTER_IMAGE_NAME
          sudo sealos save $CLUSTER_IMAGE_NAME -o $RUNTIME_NAME.tar
      - name: Upload cluster image tar
        run: |
          sudo -v ; curl https://gosspublic.alicdn.com/ossutil/install.sh | sudo bash
          ossutil64 cp -e ${{ secrets.OSS_ENDPOINT }} \
            -i ${{ secrets.OSS_ACCESS_KEY_ID }} \
            -k ${{ secrets.OSS_ACCESS_KEY_SECRET }} \
            $RUNTIME_NAME.tar \
            oss://${{ secrets.OSS_BUCKET }}/cloud/devbox/runtime/$RUNTIME_NAME.tar
