apiVersion: devbox.sealos.io/v1alpha1
kind: Runtime
metadata:
  name: nginx-1-22-1-2024-11-18-0836
  namespace: devbox-system
  annotations:
    devbox.sealos.io/defaultVersion: "false"
spec:
  classRef: nginx
  config:
    image: ghcr.io/labring-actions/devbox/nginx-1.22.1:62f0cfe
    ports:
      - containerPort: 22
        name: devbox-ssh-port
        protocol: TCP
    appPorts:
      - port: 80
        name: devbox-app-port
        protocol: TCP
    user: devbox
    workingDir: /home/devbox/project
    releaseCommand:
      - /bin/bash
      - -c
    releaseArgs:
      - /home/devbox/project/entrypoint.sh
  description: nginx 1.22.1
  version: "1.22.1"
  runtimeVersion: 2024-11-18-0836
  state: active  
---
apiVersion: devbox.sealos.io/v1alpha1
kind: RuntimeClass
metadata:
  name: nginx
spec:
  title: "nginx"
  kind: Framework
  description: nginx
